# This is a basic workflow to help you get started with Actions

name: CI/CD Preview

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Install Node.js
      uses: actions/setup-node@v3.3.0
      with:
        node-version: 16.15.1
    
    - name: Install NPM packages
      run: npm ci
    
    - name: Build project
      run: npm run build

    - name: Upload production-ready build files
      uses: actions/upload-artifact@v2
      with:
        name: production-files
        path: ./build

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: production-files
        path: ./build

    - name: Deploy to build branch
      uses: peaceiris/actions-gh-pages@v3
      with:
        target_branch: build
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build
  
  comment:
    name: Give a comment on Pull Request
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/github-script@v5
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'To see preview, visit [here](https://github.com/reskimulud)'
            })
